name = "geno-visualizer"
compatibility_date = "2024-08-06"
compatibility_flags = ["nodejs_compat"]
main = "worker.js"

[assets]
directory = "./crates/app-web"
binding = "ASSETS"
html_handling = "auto-trailing-slash"
not_found_handling = "single-page-application"

[vars]
ENVIRONMENT = "production"

# [[routes]]
# pattern = "your-subdomain.yourdomain.tld/*"
# zone_name = "yourdomain.tld"

[build]
command = "npm run build:web"

[dev]
port = 8787
local_protocol = "https"
upstream_protocol = "https"
