name = "geno-visualizer"
compatibility_date = "2024-08-06"
compatibility_flags = ["nodejs_compat"]
main = "worker.js"

[assets]
directory = "./dist"
binding = "ASSETS"
html_handling = "auto-trailing-slash"
not_found_handling = "single-page-application"

[vars]
ENVIRONMENT = "production"

[[routes]]
pattern = "geno-1.tre.systems/*"
zone_name = "tre.systems"

[build]
command = "npm run build"

[dev]
port = 8787
local_protocol = "https"
upstream_protocol = "https"
